#!/bin/bash
# This file is AUTO-GENERATED by scripts/generate-localstack-setup.ts
# DO NOT EDIT MANUALLY - Changes will be overwritten
# To update: Run `pnpm run sync-schema` in the root directory

set -e

ENDPOINT="http://localhost:4566"
REGION="ap-northeast-1"

echo "========================================="
echo "LocalStack Setup for Timtam"
echo "========================================="
echo "Endpoint: $ENDPOINT"
echo "Region: $REGION"
echo ""

# Wait for LocalStack
echo "Waiting for LocalStack to be ready..."
max_attempts=30
attempt=0
until curl -s "$ENDPOINT/_localstack/health" > /dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ $attempt -ge $max_attempts ]; then
    echo "ERROR: LocalStack did not start within expected time"
    exit 1
  fi
  echo "Attempt $attempt/$max_attempts..."
  sleep 2
done
echo "✓ LocalStack is ready"
echo ""

# DynamoDB Tables
echo "Creating DynamoDB tables..."
echo ""

# timtam-media-pipelines
aws dynamodb create-table \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-media-pipelines \
  --attribute-definitions \
    AttributeName=meetingId,AttributeType=S \
  --key-schema \
    AttributeName=meetingId,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST \
  > /dev/null 2>&1 || echo "  → timtam-media-pipelines already exists"
echo "✓ timtam-media-pipelines"

# timtam-ai-messages
aws dynamodb create-table \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-ai-messages \
  --attribute-definitions \
    AttributeName=meetingId,AttributeType=S \
    AttributeName=timestamp,AttributeType=N \
  --key-schema \
    AttributeName=meetingId,KeyType=HASH \
    AttributeName=timestamp,KeyType=RANGE \
  --billing-mode PAY_PER_REQUEST \
  > /dev/null 2>&1 || echo "  → timtam-ai-messages already exists"
echo "✓ timtam-ai-messages"

# TTL for timtam-ai-messages
aws dynamodb update-time-to-live \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-ai-messages \
  --time-to-live-specification "Enabled=true,AttributeName=ttl" \
  > /dev/null 2>&1 || true

# timtam-meetings-metadata
aws dynamodb create-table \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-meetings-metadata \
  --attribute-definitions \
    AttributeName=meetingId,AttributeType=S \
    AttributeName=meetingCode,AttributeType=S \
  --key-schema \
    AttributeName=meetingId,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST \
  --global-secondary-indexes '[{"IndexName":"meetingCode-index","KeySchema":[{"AttributeName":"meetingCode","KeyType":"HASH"}],"Projection":{"ProjectionType":"ALL"}}]' \
  > /dev/null 2>&1 || echo "  → timtam-meetings-metadata already exists"
echo "✓ timtam-meetings-metadata"

# timtam-orchestrator-config
aws dynamodb create-table \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-orchestrator-config \
  --attribute-definitions \
    AttributeName=configKey,AttributeType=S \
  --key-schema \
    AttributeName=configKey,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST \
  > /dev/null 2>&1 || echo "  → timtam-orchestrator-config already exists"
echo "✓ timtam-orchestrator-config"

# timtam-grasp-configs
aws dynamodb create-table \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --table-name timtam-grasp-configs \
  --attribute-definitions \
    AttributeName=configId,AttributeType=S \
  --key-schema \
    AttributeName=configId,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST \
  > /dev/null 2>&1 || echo "  → timtam-grasp-configs already exists"
echo "✓ timtam-grasp-configs"


# SQS Queues
echo "Creating SQS queues..."
echo ""

# transcript-asr-dlq.fifo
TRANSCRIPTASRDLQB6E94019_URL=$(aws sqs create-queue \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-name transcript-asr-dlq.fifo \
  --attributes FifoQueue=true,MessageRetentionPeriod=1209600 \
  --query 'QueueUrl' --output text 2>/dev/null) || echo "  → transcript-asr-dlq.fifo already exists"
echo "✓ transcript-asr-dlq.fifo"

# transcript-asr.fifo
aws sqs create-queue \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-name transcript-asr.fifo \
  --attributes FifoQueue=true,ContentBasedDeduplication=true,VisibilityTimeout=30,MessageRetentionPeriod=86400 \
  > /dev/null 2>&1 || echo "  → transcript-asr.fifo already exists"
echo "✓ transcript-asr.fifo"

# Set RedrivePolicy for transcript-asr.fifo
QUEUE_URL=$(aws sqs get-queue-url \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-name transcript-asr.fifo \
  --query 'QueueUrl' --output text 2>/dev/null)
DLQ_ARN=$(aws sqs get-queue-attributes \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-url "${TRANSCRIPTASRDLQB6E94019_URL}" \
  --attribute-names QueueArn \
  --query 'Attributes.QueueArn' --output text 2>/dev/null)
REDRIVE_POLICY=$(jq -n \
  --arg arn "$DLQ_ARN" \
  --argjson max 3 \
  '{deadLetterTargetArn: $arn, maxReceiveCount: $max}')
ATTRIBUTES=$(jq -n --argjson policy "$REDRIVE_POLICY" '{RedrivePolicy: ($policy | tostring)}')
aws sqs set-queue-attributes \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-url "$QUEUE_URL" \
  --attributes "$ATTRIBUTES" \
  > /dev/null 2>&1 || true

# OrchestratorControlQueue
aws sqs create-queue \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  --queue-name OrchestratorControlQueue \
  --attributes VisibilityTimeout=10,MessageRetentionPeriod=86400 \
  > /dev/null 2>&1 || echo "  → OrchestratorControlQueue already exists"
echo "✓ OrchestratorControlQueue"


# S3 Bucket (manually maintained)
echo "Creating S3 bucket..."

aws s3 mb s3://timtam-local-dev \
  --endpoint-url "$ENDPOINT" \
  --region "$REGION" \
  > /dev/null 2>&1 || echo "  → timtam-local-dev already exists"

echo "✓ timtam-local-dev"

echo ""
echo "========================================="
echo "LocalStack setup complete!"
echo "========================================="
